server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/file-service?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8280/realms/markie
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
app:
  file:
    storage-dir: C:\uploads
    download-prefix: http://localhost:8888/file/media/download/